export const countries = [
    {
      name: "Afghanistan",
      phoneCode: "93",
      flagClassCode: "af",
      format: "07 0123 4567",
    },
    {
      name: "Albania",
      phoneCode: "355",
      flagClassCode: "al",
      format: "067 212 3456",
    },
    {
      name: "Algeria",
      phoneCode: "213",
      flagClassCode: "dz",
      format: "055 123 4567",
    },
    {
      name: "American Samoa",
      phoneCode: "1",
      flagClassCode: "as",
      format: "(684) 733-1234",
    },
    {
      name: "Andorra",
      phoneCode: "376",
      flagClassCode: "ad",
      format: "312 345",
    },
    {
      name: "Angola",
      phoneCode: "244",
      flagClassCode: "ao",
      format: "923 123 456",
    },
    {
      name: "Anguilla",
      phoneCode: "1",
      flagClassCode: "ai",
      format: "(264) 235-1234",
    },
    {
      name: "Antigua and Barbuda",
      phoneCode: "1",
      flagClassCode: "ag",
      format: "(268) 464 1234",
    },
    {
      name: "Argentina",
      phoneCode: "54",
      flagClassCode: "ar",
      format: "11 2345 6789",
    },
    {
      name: "Armenia",
      phoneCode: "374",
      flagClassCode: "am",
      format: "077 123456",
    },
    {
      name: "Aruba",
      phoneCode: "297",
      flagClassCode: "aw",
      format: "560 1234",
    },
    {
      name: "Australia",
      phoneCode: "61",
      flagClassCode: "au",
      format: "0412 345 678",
    },
    {
      name: "Austria",
      phoneCode: "43",
      flagClassCode: "at",
      format: "0664 123456",
    },
    {
      name: "Azerbaijan",
      phoneCode: "994",
      flagClassCode: "az",
      format: "040 123 45 67",
    },
    {
      name: "Bahamas",
      phoneCode: "1",
      flagClassCode: "bs",
      format: "(242) 359-1234",
    },
    {
      name: "Bahrain",
      phoneCode: "973",
      flagClassCode: "bh",
      format: "3600 1234",
    },
    {
      name: "Bangladesh",
      phoneCode: "880",
      flagClassCode: "bd",
      format: "01812-345678",
    },
    {
      name: "Barbados",
      phoneCode: "1",
      flagClassCode: "bb",
      format: "(246) 250-1234",
    },
    {
      name: "Belarus",
      phoneCode: "375",
      flagClassCode: "by",
      format: "8 029 491-19-11",
    },
    {
      name: "Belgium",
      phoneCode: "32",
      flagClassCode: "be",
      format: "0470 12 34 56",
    },
    {
      name: "Belize",
      phoneCode: "501",
      flagClassCode: "bz",
      format: "622-1234",
    },
    {
      name: "Benin",
      phoneCode: "229",
      flagClassCode: "bj",
      format: "90 01 12 34",
    },
    {
      name: "Bermuda",
      phoneCode: "1",
      flagClassCode: "bm",
      format: "(441) 370-1234",
    },
    {
      name: "Bhutan",
      phoneCode: "975",
      flagClassCode: "bt",
      format: "17 12 34 56",
    },
    {
      name: "Bolivia",
      phoneCode: "591",
      flagClassCode: "bo",
      format: "71234567",
    },
    {
      name: "Bosnia and Herzegovina",
      phoneCode: "387",
      flagClassCode: "ba",
      format: "061 123 456",
    },
    {
      name: "Botswana",
      phoneCode: "267",
      flagClassCode: "bw",
      format: "71 123 456",
    },
    {
      name: "Brazil",
      phoneCode: "55",
      flagClassCode: "br",
      format: "(11) 96123-4567",
    },
    {
      name: "British Indian Ocean Territory",
      phoneCode: "246",
      flagClassCode: "io",
      format: "380 1234",
    },
    {
      name: "British Virgin Islands",
      phoneCode: "1",
      flagClassCode: "vg",
      format: "(284) 300-1234",
    },
    {
      name: "Brunei",
      phoneCode: "673",
      flagClassCode: "bn",
      format: "712 3456",
    },
    {
      name: "Bulgaria",
      phoneCode: "359",
      flagClassCode: "bg",
      format: "048 123 456",
    },
    {
      name: "Burkina Faso",
      phoneCode: "226",
      flagClassCode: "bf",
      format: "70 12 34 56",
    },
    {
      name: "Burundi",
      phoneCode: "257",
      flagClassCode: "bi",
      format: "79 56 12 34",
    },
    {
      name: "Cambodia",
      phoneCode: "855",
      flagClassCode: "kh",
      format: "091 234 567",
    },
    {
      name: "Cameroon",
      phoneCode: "237",
      flagClassCode: "cm",
      format: "6 71 23 45 67",
    },
    {
      name: "Canada",
      phoneCode: "1",
      flagClassCode: "ca",
      format: "(204) 234-5678",
    },
    {
      name: "Cape Verde",
      phoneCode: "238",
      flagClassCode: "cv",
      format: "991 12 34",
    },
    {
      name: "Caribbean Netherlands",
      phoneCode: "599",
      flagClassCode: "bq",
      format: "318 1234",
    },
    {
      name: "Cayman Islands",
      phoneCode: "1",
      flagClassCode: "ky",
      format: "(345) 323-1234",
    },
    {
      name: "Central African Republic",
      phoneCode: "236",
      flagClassCode: "cf",
      format: "70 01 23 45",
    },
    {
      name: "Chad",
      phoneCode: "235",
      flagClassCode: "td",
      format: "63 01 23 45",
    },
    {
      name: "Chile",
      phoneCode: "56",
      flagClassCode: "cl",
      format: "09 6123 4567",
    },
    {
      name: "China",
      phoneCode: "86",
      flagClassCode: "cn",
      format: "131 2345 6789",
    },
    {
      name: "Christmas Island",
      phoneCode: "61",
      flagClassCode: "cx",
      format: "0412 345 678",
    },
    {
      name: "Cocos (Keeling) Islands",
      phoneCode: "61",
      flagClassCode: "cc",
      format: "0412 345 678",
    },
    {
      name: "Colombia",
      phoneCode: "57",
      flagClassCode: "co",
      format: "321 1234567",
    },
    {
      name: "Comoros",
      phoneCode: "269",
      flagClassCode: "km",
      format: "321 23 45",
    },
    {
      name: "Congo (DRC)",
      phoneCode: "243",
      flagClassCode: "cd",
      format: "0991 234 567",
    },
    {
      name: "Congo (Republic)",
      phoneCode: "242",
      flagClassCode: "cg",
      format: "06 123 4567",
    },
    {
      name: "Cook Islands",
      phoneCode: "682",
      flagClassCode: "ck",
      format: "71 234",
    },
    {
      name: "Costa Rica",
      phoneCode: "506",
      flagClassCode: "cr",
      format: "8312 3456",
    },
    {
      name: "Côte d’Ivoire",
      phoneCode: "225",
      flagClassCode: "ci",
      format: "01 23 45 67",
    },
    {
      name: "Croatia",
      phoneCode: "385",
      flagClassCode: "hr",
      format: "091 234 5678",
    },
    {
      name: "Cuba",
      phoneCode: "53",
      flagClassCode: "cu",
      format: "05 1234567",
    },
    {
      name: "Curaçao",
      phoneCode: "599",
      flagClassCode: "cw",
      format: "9 518 1234",
    },
    {
      name: "Cyprus",
      phoneCode: "357",
      flagClassCode: "cy",
      format: "96 123456",
    },
    {
      name: "Czech Republic",
      phoneCode: "420",
      flagClassCode: "cz",
      format: "601 123 456",
    },
    {
      name: "Denmark",
      phoneCode: "45",
      flagClassCode: "dk",
      format: "20 12 34 56",
    },
    {
      name: "Djibouti",
      phoneCode: "253",
      flagClassCode: "dj",
      format: "77 83 10 01",
    },
    {
      name: "Dominica",
      phoneCode: "1",
      flagClassCode: "dm",
      format: "(767) 225-1234",
    },
    {
      name: "Dominican Republic",
      phoneCode: "1",
      flagClassCode: "do",
      format: "(809) 234-5678",
    },
    {
      name: "Ecuador",
      phoneCode: "593",
      flagClassCode: "ec",
      format: "099 123 4567",
    },
    {
      name: "Egypt",
      phoneCode: "20",
      flagClassCode: "eg",
      format: "0100 123 4567",
    },
    {
      name: "El Salvador",
      phoneCode: "503",
      flagClassCode: "sv",
      format: "7012 3456",
    },
    {
      name: "Equatorial Guinea",
      phoneCode: "240",
      flagClassCode: "gq",
      format: "222 123 456",
    },
    {
      name: "Eritrea",
      phoneCode: "291",
      flagClassCode: "er",
      format: "07 123 456",
    },
    {
      name: "Estonia",
      phoneCode: "372",
      flagClassCode: "ee",
      format: "5123 4567",
    },
    {
      name: "Ethiopia",
      phoneCode: "251",
      flagClassCode: "et",
      format: "091 123 4567",
    },
    {
      name: "Falkland Islands",
      phoneCode: "500",
      flagClassCode: "fk",
      format: "51234",
    },
    {
      name: "Faroe Islands",
      phoneCode: "298",
      flagClassCode: "fo",
      format: "211234",
    },
    {
      name: "Fiji",
      phoneCode: "679",
      flagClassCode: "fj",
      format: "701 2345",
    },
    {
      name: "Finland",
      phoneCode: "358",
      flagClassCode: "fi",
      format: "041 2345678",
    },
    {
      name: "France",
      phoneCode: "33",
      flagClassCode: "fr",
      format: "06 12 34 56 78",
    },
    {
      name: "French Guiana",
      phoneCode: "594",
      flagClassCode: "gf",
      format: "0694 20 12 34",
    },
    {
      name: "French Polynesia",
      phoneCode: "689",
      flagClassCode: "pf",
      format: "87 12 34 56",
    },
    {
      name: "Gabon",
      phoneCode: "241",
      flagClassCode: "ga",
      format: "06 03 12 34",
    },
    {
      name: "Gambia",
      phoneCode: "220",
      flagClassCode: "gm",
      format: "301 2345",
    },
    {
      name: "Georgia",
      phoneCode: "995",
      flagClassCode: "ge",
      format: "555 12 34 56",
    },
    {
      name: "Germany",
      phoneCode: "49",
      flagClassCode: "de",
      format: "01512 3456789",
    },
    {
      name: "Ghana",
      phoneCode: "233",
      flagClassCode: "gh",
      format: "023 123 4567",
    },
    {
      name: "Gibraltar",
      phoneCode: "350",
      flagClassCode: "gi",
      format: "57123456",
    },
    {
      name: "Greece",
      phoneCode: "30",
      flagClassCode: "gr",
      format: "691 234 5678",
    },
    {
      name: "Greenland",
      phoneCode: "299",
      flagClassCode: "gl",
      format: "22 12 34",
    },
    {
      name: "Grenada",
      phoneCode: "1",
      flagClassCode: "gd",
      format: "(473) 403-1234",
    },
    {
      name: "Guadeloupe",
      phoneCode: "590",
      flagClassCode: "gp",
      format: "0690 20 12 34",
    },
    {
      name: "Guam",
      phoneCode: "1",
      flagClassCode: "gu",
      format: "(671) 300-1234",
    },
    {
      name: "Guatemala",
      phoneCode: "502",
      flagClassCode: "gt",
      format: "5123 4567",
    },
    {
      name: "Guernsey",
      phoneCode: "44",
      flagClassCode: "gg",
      format: "07781 123456",
    },
    {
      name: "Guinea",
      phoneCode: "224",
      flagClassCode: "gn",
      format: "601 12 34 56",
    },
    {
      name: "Guinea-Bissau",
      phoneCode: "245",
      flagClassCode: "gw",
      format: "955 012 345",
    },
    {
      name: "Guyana",
      phoneCode: "592",
      flagClassCode: "gy",
      format: "609 1234",
    },
    {
      name: "Haiti",
      phoneCode: "509",
      flagClassCode: "ht",
      format: "34 10 1234",
    },
    {
      name: "Honduras",
      phoneCode: "504",
      flagClassCode: "hn",
      format: "9123-4567",
    },
    {
      name: "Hong Kong",
      phoneCode: "852",
      flagClassCode: "hk",
      format: "5123 4567",
    },
    {
      name: "Hungary",
      phoneCode: "36",
      flagClassCode: "hu",
      format: "(20) 123 4567",
    },
    {
      name: "Iceland",
      phoneCode: "354",
      flagClassCode: "is",
      format: "611 1234",
    },
    {
      name: "India",
      phoneCode: "91",
      flagClassCode: "in",
      format: "081234 56789",
    },
    {
      name: "Indonesia",
      phoneCode: "62",
      flagClassCode: "id",
      format: "0812-345-678",
    },
    {
      name: "Iran",
      phoneCode: "98",
      flagClassCode: "ir",
      format: "0912 345 6789",
    },
    {
      name: "Iraq",
      phoneCode: "964",
      flagClassCode: "iq",
      format: "0791 234 5678",
    },
    {
      name: "Ireland",
      phoneCode: "353",
      flagClassCode: "ie",
      format: "085 012 3456",
    },
    {
      name: "Israel",
      phoneCode: "972",
      flagClassCode: "il",
      format: "050-123-4567",
    },
    {
      name: "Italy",
      phoneCode: "39",
      flagClassCode: "it",
      format: "312 345 6789",
    },
    {
      name: "Jamaica",
      phoneCode: "1-876",
      flagClassCode: "jm",
      format: "(876) 210-1234",
    },
    {
      name: "Japan",
      phoneCode: "81",
      flagClassCode: "jp",
      format: "090-1234-5678",
    },
    {
      name: "Jordan",
      phoneCode: "962",
      flagClassCode: "jo",
      format: "07 9012 3456",
    },
    {
      name: "Kazakhstan",
      phoneCode: "7",
      flagClassCode: "kz",
      format: "8 (771) 000 9998",
    },
    {
      name: "Kenya",
      phoneCode: "254",
      flagClassCode: "ke",
      format: "0712 123456",
    },
    {
      name: "Kiribati",
      phoneCode: "686",
      flagClassCode: "ki",
      format: "72001234",
    },
    {
      name: "Kuwait",
      phoneCode: "965",
      flagClassCode: "kw",
      format: "500 12345",
    },
    {
      name: "Kyrgyzstan",
      phoneCode: "996",
      flagClassCode: "kg",
      format: "0700 123 456",
    },
    {
      name: "Laos",
      phoneCode: "856",
      flagClassCode: "la",
      format: "020 23 123 456",
    },
    {
      name: "Latvia",
      phoneCode: "371",
      flagClassCode: "lv",
      format: "21 234 567",
    },
    {
      name: "Lebanon",
      phoneCode: "961",
      flagClassCode: "lb",
      format: "71 123 456",
    },
    {
      name: "Lesotho",
      phoneCode: "266",
      flagClassCode: "ls",
      format: "5012 3456",
    },
    {
      name: "Liberia",
      phoneCode: "231",
      flagClassCode: "lr",
      format: "077 012 3456",
    },
    {
      name: "Libya",
      phoneCode: "218",
      flagClassCode: "ly",
      format: "091-2345678",
    },
    {
      name: "Liechtenstein",
      phoneCode: "423",
      flagClassCode: "li",
      format: "660 234 567",
    },
    {
      name: "Lithuania",
      phoneCode: "370",
      flagClassCode: "lt",
      format: "(8-612) 34567",
    },
    {
      name: "Luxembourg",
      phoneCode: "352",
      flagClassCode: "lu",
      format: "628 123 456",
    },
    {
      name: "Macau",
      phoneCode: "853",
      flagClassCode: "mo",
      format: "6612 3456",
    },
    {
      name: "Macedonia",
      phoneCode: "389",
      flagClassCode: "mk",
      format: "072 345 678",
    },
    {
      name: "Madagascar",
      phoneCode: "261",
      flagClassCode: "mg",
      format: "032 12 345 67",
    },
    {
      name: "Malawi",
      phoneCode: "265",
      flagClassCode: "mw",
      format: "0991 23 45 67",
    },
    {
      name: "Malaysia",
      phoneCode: "60",
      flagClassCode: "my",
      format: "012-345 6789",
    },
    {
      name: "Maldives",
      phoneCode: "960",
      flagClassCode: "mv",
      format: "771-2345",
    },
    {
      name: "Mali",
      phoneCode: "223",
      flagClassCode: "ml",
      format: "65 01 23 45",
    },
    {
      name: "Malta",
      phoneCode: "356",
      flagClassCode: "mt",
      format: "9696 1234",
    },
    {
      name: "Marshall Islands",
      phoneCode: "692",
      flagClassCode: "mh",
      format: "235-1234",
    },
    {
      name: "Mauritania",
      phoneCode: "222",
      flagClassCode: "mr",
      format: "22 12 34 56",
    },
    {
      name: "Mauritius",
      phoneCode: "230",
      flagClassCode: "mu",
      format: "5251 2345",
    },
    {
      name: "Mexico",
      phoneCode: "52",
      flagClassCode: "mx",
      format: "044 222 123 4567",
    },
    {
      name: "Micronesia",
      phoneCode: "691",
      flagClassCode: "fm",
      format: "350 1234",
    },
    {
      name: "Moldova",
      phoneCode: "373",
      flagClassCode: "md",
      format: "0621 12 345",
    },
    {
      name: "Monaco",
      phoneCode: "377",
      flagClassCode: "mc",
      format: "06 12 34 56 78",
    },
    {
      name: "Mongolia",
      phoneCode: "976",
      flagClassCode: "mn",
      format: "8812 3456",
    },
    {
      name: "Montenegro",
      phoneCode: "382",
      flagClassCode: "me",
      format: "067 622 901",
    },
    {
      name: "Morocco",
      phoneCode: "212",
      flagClassCode: "ma",
      format: "0650-123456",
    },
    {
      name: "Mozambique",
      phoneCode: "258",
      flagClassCode: "mz",
      format: "82 123 4567",
    },
    {
      name: "Myanmar",
      phoneCode: "95",
      flagClassCode: "mm",
      format: "09 212 3456",
    },
    {
      name: "Namibia",
      phoneCode: "264",
      flagClassCode: "na",
      format: "081 123 4567",
    },
    {
      name: "Nauru",
      phoneCode: "674",
      flagClassCode: "nr",
      format: "555 1234",
    },
    {
      name: "Nepal",
      phoneCode: "977",
      flagClassCode: "np",
      format: "984-1234567",
    },
    {
      name: "Netherlands",
      phoneCode: "31",
      flagClassCode: "nl",
      format: "06 12345678",
    },
    {
      name: "New Zealand",
      phoneCode: "64",
      flagClassCode: "nz",
      format: "021 123 4567",
    },
    {
      name: "Nicaragua",
      phoneCode: "505",
      flagClassCode: "ni",
      format: "8123 4567",
    },
    {
      name: "Niger",
      phoneCode: "227",
      flagClassCode: "ne",
      format: "93 12 34 56",
    },
    {
      name: "Nigeria",
      phoneCode: "234",
      flagClassCode: "ng",
      format: "0802 123 4567",
    },
    {
      name: "North Korea",
      phoneCode: "850",
      flagClassCode: "kp",
      format: "0192 123 4567",
    },
    {
      name: "Norway",
      phoneCode: "47",
      flagClassCode: "no",
      format: "406 12 345",
    },
    {
      name: "Oman",
      phoneCode: "968",
      flagClassCode: "om",
      format: "9212 3456",
    },
    {
      name: "Pakistan",
      phoneCode: "92",
      flagClassCode: "pk",
      format: "0301 2345678",
    },
    {
      name: "Palau",
      phoneCode: "680",
      flagClassCode: "pw",
      format: "620 1234",
    },
    {
      name: "Palestine",
      phoneCode: "970",
      flagClassCode: "ps",
      format: "0599 123 456",
    },
    {
      name: "Panama",
      phoneCode: "507",
      flagClassCode: "pa",
      format: "6123-4567",
    },
    {
      name: "Papua New Guinea",
      phoneCode: "675",
      flagClassCode: "pg",
      format: "681 2345",
    },
    {
      name: "Paraguay",
      phoneCode: "595",
      flagClassCode: "py",
      format: "0961 456789",
    },
    {
      name: "Peru",
      phoneCode: "51",
      flagClassCode: "pe",
      format: "912 345 678",
    },
    {
      name: "Philippines",
      phoneCode: "63",
      flagClassCode: "ph",
      format: "0905 123 4567",
    },
    {
      name: "Poland",
      phoneCode: "48",
      flagClassCode: "pl",
      format: "512 345 678",
    },
    {
      name: "Portugal",
      phoneCode: "351",
      flagClassCode: "pt",
      format: "912 345 678",
    },
    {
      name: "Puerto Rico",
      phoneCode: "1-787",
      flagClassCode: "pr",
      format: "(787) 234-5678",
    },
    {
      name: "Qatar",
      phoneCode: "974",
      flagClassCode: "qa",
      format: "3312 3456",
    },
    {
      name: "Romania",
      phoneCode: "40",
      flagClassCode: "ro",
      format: "0712 034 567",
    },
    {
      name: "Russia",
      phoneCode: "7",
      flagClassCode: "ru",
      format: "8 (912) 345-67-89",
    },
    {
      name: "Rwanda",
      phoneCode: "250",
      flagClassCode: "rw",
      format: "0720 123 456",
    },
    {
      name: "Saint Kitts and Nevis",
      phoneCode: "1-869",
      flagClassCode: "kn",
      format: "(869) 765-2917",
    },
    {
      name: "Saint Lucia",
      phoneCode: "1-758",
      flagClassCode: "lc",
      format: "(758) 284-5678",
    },
    {
      name: "Saint Vincent and the Grenadines",
      phoneCode: "1-784",
      flagClassCode: "vc",
      format: "(784) 430-1234",
    },
    {
      name: "Samoa",
      phoneCode: "685",
      flagClassCode: "ws",
      format: "72 12345",
    },
    {
      name: "San Marino",
      phoneCode: "378",
      flagClassCode: "sm",
      format: "66 66 12 12",
    },
    {
      name: "Sao Tome and Principe",
      phoneCode: "239",
      flagClassCode: "st",
      format: "981 2345",
    },
    {
      name: "Saudi Arabia",
      phoneCode: "966",
      flagClassCode: "sa",
      format: "051 234 5678",
    },
    {
      name: "Senegal",
      phoneCode: "221",
      flagClassCode: "sn",
      format: "70 123 45 67",
    },

    {
      name: "Serbia",
      phoneCode: "381",
      flagClassCode: "rs",
      format: "060 1234567",
    },
    {
      name: "Seychelles",
      phoneCode: "248",
      flagClassCode: "sc",
      format: "2 510 123",
    },
    {
      name: "Sierra Leone",
      phoneCode: "232",
      flagClassCode: "sl",
      format: "(025) 123456",
    },
    {
      name: "Singapore",
      phoneCode: "65",
      flagClassCode: "sg",
      format: "8123 4567",
    },
    {
      name: "Slovakia",
      phoneCode: "421",
      flagClassCode: "sk",
      format: "0912 123 456",
    },
    {
      name: "Slovenia",
      phoneCode: "386",
      flagClassCode: "si",
      format: "031 234 567",
    },
    {
      name: "Solomon Islands",
      phoneCode: "677",
      flagClassCode: "sb",
      format: "74 21234",
    },
    {
      name: "Somalia",
      phoneCode: "252",
      flagClassCode: "so",
      format: "7 1123456",
    },
    {
      name: "South Africa",
      phoneCode: "27",
      flagClassCode: "za",
      format: "071 123 4567",
    },
    {
      name: "South Korea",
      phoneCode: "82",
      flagClassCode: "kr",
      format: "010-2000-0000",
    },
    {
      name: "South Sudan",
      phoneCode: "211",
      flagClassCode: "ss",
      format: "0977 123 456",
    },
    {
      name: "Spain",
      phoneCode: "34",
      flagClassCode: "es",
      format: "612 34 56 78",
    },
    {
      name: "Sri Lanka",
      phoneCode: "94",
      flagClassCode: "lk",
      format: "071 234 5678",
    },
    {
      name: "Sudan",
      phoneCode: "249",
      flagClassCode: "sd",
      format: "091 123 1234",
    },
    {
      name: "Suriname",
      phoneCode: "597",
      flagClassCode: "sr",
      format: "741-2345",
    },
    {
      name: "Swaziland",
      phoneCode: "268",
      flagClassCode: "sz",
      format: "7612 3456",
    },
    {
      name: "Sweden",
      phoneCode: "46",
      flagClassCode: "se",
      format: "070-123 45 67",
    },
    {
      name: "Switzerland",
      phoneCode: "41",
      flagClassCode: "ch",
      format: "078 123 45 67",
    },
    {
      name: "Syria",
      phoneCode: "963",
      flagClassCode: "sy",
      format: "0944 567 890",
    },
    {
      name: "Taiwan",
      phoneCode: "886",
      flagClassCode: "tw",
      format: "0912 345 678",
    },
    {
      name: "Tajikistan",
      phoneCode: "992",
      flagClassCode: "tj",
      format: "917 12 3456",
    },
    {
      name: "Tanzania",
      phoneCode: "255",
      flagClassCode: "tz",
      format: "0621 234 567",
    },
    {
      name: "Thailand",
      phoneCode: "66",
      flagClassCode: "th",
      format: "081 234 5678",
    },
    {
      name: "Togo",
      phoneCode: "228",
      flagClassCode: "tg",
      format: "90 11 23 45",
    },
    {
      name: "Tonga",
      phoneCode: "676",
      flagClassCode: "to",
      format: "771 5123",
    },
    {
      name: "Trinidad and Tobago",
      phoneCode: "1-868",
      flagClassCode: "tt",
      format: "(868) 291-1234",
    },
    {
      name: "Tunisia",
      phoneCode: "216",
      flagClassCode: "tn",
      format: "20 123 456",
    },
    {
      name: "Turkey",
      phoneCode: "90",
      flagClassCode: "tr",
      format: "0501 234 5678",
    },
    {
      name: "Turkmenistan",
      phoneCode: "993",
      flagClassCode: "tm",
      format: "8 66 123456",
    },
    {
      name: "Tuvalu",
      phoneCode: "688",
      flagClassCode: "tv",
      format: "901234",
    },
    {
      name: "Uganda",
      phoneCode: "256",
      flagClassCode: "ug",
      format: "0712 345678",
    },
    {
      name: "Ukraine",
      phoneCode: "380",
      flagClassCode: "ua",
      format: "050 123 4567",
    },
    {
      name: "United Arab Emirates",
      phoneCode: "971",
      flagClassCode: "ae",
      format: "050 123 4567",
    },
    {
      name: "United Kingdom",
      phoneCode: "44",
      flagClassCode: "gb",
      format: "07400 123456",
    },
    {
      name: "United States",
      phoneCode: "1",
      flagClassCode: "us",
      format: "(201) 555-0123",
    },
    {
      name: "Uruguay",
      phoneCode: "598",
      flagClassCode: "uy",
      format: "094 231 234",
    },
    {
      name: "Uzbekistan",
      phoneCode: "998",
      flagClassCode: "uz",
      format: "8 91 234 56 78",
    },
    {
      name: "Vanuatu",
      phoneCode: "678",
      flagClassCode: "vu",
      format: "591 2345",
    },
    {
      name: "Vatican City",
      phoneCode: "39-06",
      flagClassCode: "va",
      format: "312 345 6789",
    },
    {
      name: "Venezuela",
      phoneCode: "58",
      flagClassCode: "ve",
      format: "0412-1234567",
    },
    {
      name: "Vietnam",
      phoneCode: "84",
      flagClassCode: "vn",
      format: "091 234 56 78",
    },
    {
      name: "Virgin Islands",
      phoneCode: "1-340",
      flagClassCode: "vi",
      format: "(340) 642-1234",
    },
    {
      name: "Yemen",
      phoneCode: "967",
      flagClassCode: "ye",
      format: "0712 345 678",
    },
    {
      name: "Zambia",
      phoneCode: "260",
      flagClassCode: "zm",
      format: "095 5123456",
    },
    {
      name: "Zimbabwe",
      phoneCode: "263",
      flagClassCode: "zw",
      format: "071 234 5678",
    },
  ];